/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daw.AdrianPerezGomez;

import java.awt.GridLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author adrian
 */
public class JuegoVida extends javax.swing.JFrame {

    /**
     * Creates new form JuegoVida
     */
    
    //Atributos
    
    private int numeroCelulas; // Numeoro de celulas en x e y
    private Generacion uno;
    private Generacion dos;
    
    public JuegoVida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelNumCel = new javax.swing.JTextField();
        btnValidar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        celulasAleatorias = new javax.swing.JButton();
        Izq = new javax.swing.JPanel();
        Der = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Top.setBackground(new java.awt.Color(194, 210, 214));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Introduce el número de células");

        labelNumCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelNumCelActionPerformed(evt);
            }
        });

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        celulasAleatorias.setText("Generar celulas aleatorias");
        celulasAleatorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celulasAleatoriasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopLayout.createSequentialGroup()
                        .addComponent(labelNumCel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnValidar))
                    .addGroup(TopLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(celulasAleatorias)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(celulasAleatorias))
                .addContainerGap())
            .addGroup(TopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelNumCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValidar))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        Izq.setBackground(new java.awt.Color(235, 189, 42));

        javax.swing.GroupLayout IzqLayout = new javax.swing.GroupLayout(Izq);
        Izq.setLayout(IzqLayout);
        IzqLayout.setHorizontalGroup(
            IzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        IzqLayout.setVerticalGroup(
            IzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        Der.setBackground(new java.awt.Color(241, 121, 19));

        javax.swing.GroupLayout DerLayout = new javax.swing.GroupLayout(Der);
        Der.setLayout(DerLayout);
        DerLayout.setHorizontalGroup(
            DerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DerLayout.setVerticalGroup(
            DerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Izq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Der, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Izq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Der, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelNumCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelNumCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelNumCelActionPerformed

    
    //Borrar lo qu epuedan tener los panales de celulas
    public void resetPaneles(){
        Der.removeAll();
        Izq.removeAll();
        Izq.repaint();
        Der.repaint();
               
    }
    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        if (validarNumeroCelulas()) {
           // borro lo que haya y dejo los paneles limpios
           this.resetPaneles();
           
           // Creo la generacion
           uno = new Generacion(numeroCelulas);
           
           //Establezco el layout del panel
           
           Izq.setLayout(new GridLayout(numeroCelulas, numeroCelulas));
           
           for(int i=0; i< numeroCelulas; i++){
               for (int j= 0; j < numeroCelulas; j++) {
                   Celula tmp = new Celula();
                   tmp.setToolTipText(Integer.toString(i) + "," + Integer.toString(j));
                   tmp.addActionListener(e->click(tmp));
                   uno.ponerCelula(i, j, tmp);
                   Izq.add(uno.getCelula(i, j));
               }
           }
           Izq.validate();
        }
        else{
            JOptionPane.showMessageDialog(this,"Número incorrecto o mal formateado");
        }
    }//GEN-LAST:event_btnValidarActionPerformed

    // Sirve para saber si lo que vas a tener la caja de texto
    // es de tipo numérico
    
    public void click(Celula tmp){
        if (tmp.isEstado()) {
            tmp.matar();
        }else{
            tmp.resucitar();
        }
    }
    public boolean esNumero(String tmp){
        try{
            Integer.parseInt(tmp);
        }catch(NumberFormatException e){
            return false;
        }
        return true;
    }
    
    // Inicializa el numero de celulas si es un rango válido, devuelvo true
    
    public boolean validarNumeroCelulas(){
        if (esNumero(labelNumCel.getText())) {
            numeroCelulas = Integer.parseInt(labelNumCel.getText());
            if (numeroCelulas>=5 && numeroCelulas<=70) {
                return true;
            }
        }
        return false;
    }
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void celulasAleatoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celulasAleatoriasActionPerformed
       
         if (validarNumeroCelulas()) {
           // borro lo que haya y dejo los paneles limpios
           this.resetPaneles();
           
           // Creo la generacion
           uno = new Generacion(numeroCelulas);
           
           //Establezco el layout del panel
           
           Izq.setLayout(new GridLayout(numeroCelulas, numeroCelulas));
           
           for(int i=0; i< numeroCelulas; i++){
               for (int j= 0; j < numeroCelulas; j++) {
                   int estado = Generacion.generacionEstado();
                   Celula tmp = Celula.generacionCelulas(estado);
                   tmp.setToolTipText(Integer.toString(i) + "," + Integer.toString(j));
                   tmp.addActionListener(e->click(tmp));
                   uno.ponerCelula(i, j, tmp);
                   Izq.add(uno.getCelula(i, j));
               }
           }
           Izq.validate();
        }
        else{
            JOptionPane.showMessageDialog(this,"Número incorrecto o mal formateado");
        }
        
        
    }//GEN-LAST:event_celulasAleatoriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoVida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoVida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoVida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoVida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoVida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Der;
    private javax.swing.JPanel Izq;
    private javax.swing.JPanel Top;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnValidar;
    private javax.swing.JButton celulasAleatorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField labelNumCel;
    // End of variables declaration//GEN-END:variables
}
